### ISSUE TITLE
Problem that calculated values are 0

### ISSUE THREAD

**Issue by frontendschlampe** [scout-app/scout-app#156]
I have a problem with Scout 0.7.1 ... sometime calculated values become result 0.

here some example code with the calculation of "width":

SASS:
```css
#header {
	img {
		@include center-block();
   		width: ceil($width-sm * 0.4);
    		padding: 20px;
  		@media (min-width: $screen-md-min) {
    			width: ceil($width-md * 0.4);
    		}
    		@media (min-width: $screen-lg-min) {
    			width: ceil($width-lg * 0.4);
    		}
	}
}
```

compiled CSS:
```css
#header img {
	display: block;
	margin-left: auto;
	margin-right: auto;
	width: 0px;
	padding: 20px;
}
@media (min-width: 992px) {
	#header img {
		width: 0px;
	}
}
@media (min-width: 1200px) {
	#header img {
		width: 0px;
	}
}
```

should be compiled CSS:
```css
#header img {
	display: block;
	margin-left: auto;
	margin-right: auto;
	width: 308px;
	padding: 20px;
}
@media (min-width: 992px) {
	#header img {
		width: 397px;
	}
}
@media (min-width: 1200px) {
	#header img {
		width: 480px;
	}
}
```

I tried to compile with LiveReload and everything is fine.
