### ISSUE TITLE
Autoprefixer Support

### ISSUE THREAD

**Issue by mejiaj** [scout-app/scout-app#163]
Unnecessary prefixes are still showing up when using compass/css3. This would be a great feature to always use only the necessary prefixes.

Some CSS3 features aren't even included in compass such as keyframes aren't currently supported. Using autoprefixer would fix that.

**Comment by TheJaredWilcurt** [comment]
Also requested by @blindmikey (https://github.com/scout-app/scout-app/issues/276).

**Comment by TheJaredWilcurt** [comment]
As far as Compass is concerned, it is [no longer maintained](https://github.com/Compass/compass). So if you are using it on legacy projects, you can continue to, however if you are creating new projects or maintaining an older project, it may be wise to move away from Compass towards a different mixin library that is maintained, or to create your own mixins that replace the ones you were using from Compass.

Adding Auto-Prefixer Support is a longer term feature. There are higher priority items that are of greater use to more users (like live reload) that I would place ahead of this.

I've yet to see a use case for Autoprefixer that can't be fixed by just cleaning up an existing codebase. It feels like a bandaid.

**Comment by Blindmikey** [comment]
Just adding my 2 cents, Autoprefixer allows my team to write css without having to think of which browser versions do or don't support vendor prefixes, and without using redundant mixins to cover every prefix in lieu of just writing css. 

Autoprefixer is a huge boon to our workflow, and many scss frameworks now utilize it by default such as bootstrap and foundation.

**Comment by TheJaredWilcurt** [comment]
@Blindmikey 

First off, thank you so much for creating a pull request for this feature and getting the ball rolling. I've pulled down your branch and tested it. Here's some stuff I noticed while testing it.

In your current branch if I process this file:

```sass
.test
    transition: 1s ease all
    -webkit-border-radius: 3px
    background: #1E5799
    background: -moz-linear-gradient(top, #1E5799 0%, #2989D8 50%, #207CCA 51%, #7DB9E8 100%)
    background: -webkit-linear-gradient(top, #1E5799 0%, #2989D8 50%, #207CCA 51%, #7DB9E8 100%)
    background: linear-gradient(to bottom, #1E5799 0%, #2989D8 50%, #207CCA 51%, #7DB9E8 100%)
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#1E5799', endColorstr='#7DB9E8', GradientType=0)
```

it will produce this:

```css
.test {
  -webkit-transition: 1s ease all;
  transition: 1s ease all;
  -webkit-border-radius: 3px;
  background: #1E5799;
  background: -webkit-linear-gradient(top, #1E5799 0%, #2989D8 50%, #207CCA 51%, #7DB9E8 100%);
  background: linear-gradient(to bottom, #1E5799 0%, #2989D8 50%, #207CCA 51%, #7DB9E8 100%);
  filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#1E5799', endColorstr='#7DB9E8', GradientType=0);
}
rstr='#1E5799', endColorstr='#7DB9E8', GradientType=0);
}
```

There are several problems here:

1. The output is not valid CSS.
1. A new user or someone just learning Sass will be confused to as to why Scout-App is adding new properties that they didn't want and removing properties they *do* want. Scout-App should not pretend that it's automated system knows better than the end user.
1. There is no option in the UI to enable/disable Autoprefixer. This would resolve the above two issues.
1. Errors from Autoprefixer don't seem to be surfaced currently. Ideally we would pass them into something similar to `scout.helpers.alert`. So there could be in app messages, desktop notifications, and sound effects played when there is an error.

We need to have a lot more discussion over the UX of how to give users options regarding Autoprefixer. The pull request cannot be merged in its current state as it gives a confusing user experience.

One possible solution would be to have a tab in the project settings panel to switch from a Sass settings view to an Autoprefixer view. You can see an example of this here:

* https://github.com/scout-app/scout-app/issues/316

However switching between tabbed views is out of the scope of this issue. For the time being, just throwing in an `<hr />` at the end of the existing Sass settings and then putting the UI controls there would be fine until we have a better system in place for switching tab views. Eventually this can be refactored as a plugin if we implement a plugin system.

I'd like some discussion on how best to present the options for Autoprefixer in the UI. I'll need to research more into what options it accepts and all of the queries that Browserslist accepts.
