### ISSUE TITLE
Scout not recognizing sass function 'str-slice' as a function.

### ISSUE THREAD

**Issue by MJWebsites777** [scout-app/scout-app#203]
Whenever I try to use the SASS function 'str-slice', it outputs 'str-slice(arguments)' in the CSS.
For example, if my SASS style was
```css
div {
  content: str-slice('apples', 1, 5);
}
```
the outputted CSS from Scout would be
```css
div {
  content: str-slice("apples", 1, 5);
}
```
instead of the correct CSS
```css
div {
  content: 'apple';
}
```

My SASS version is 3.4.13, and all Ruby gems are up-to-date.
