### ISSUE TITLE
Issue parsing selector with :not() when multiple parents specified in nest

### ISSUE THREAD

**Issue by Blindmikey** [scout-app/scout-app#264]
parsing 
```css
.wrapper1,
.wrapper2 {
    input[type]:not([type='submit']) {
        color: red;
    }
}
```
incorrectly parses as: 
```css
.wrapper1 input[type]:not([type='submit'], [type='submit']),
.wrapper2 input[type]:not([type='submit'], [type='submit']) {
  color: red;
}
```
should parse as:
```css
.wrapper1 input[type]:not([type='submit']),
.wrapper2 input[type]:not([type='submit']) {
  color: red;
}

```
