### ISSUE TITLE
Compass inline-image

### ISSUE THREAD

**Issue by gabyferman** [scout-app/scout-app#319]
Can I use compass inline-image with the latest version of scout?

**Comment by TheJaredWilcurt** [comment]
@gabyferman 

No. However this could be a potential plug-in in the future.

Compass (which is no longer maintained), requires Ruby to run. Scout-App 2 no longer relies on Ruby, Adobe Air, or Java to run. As such, it means that it can only support Compass mixins.

From my understanding, the functionality you are looking for is to convert an image reference to an embedded base-64 version.

So this:
```css
.thing {
    background-image: url('../my-file.gif');
}
```
becomes this
```css
.thing {
    background-image: url('data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7');
}
```

This functionality could potentially be added into Scout-App in a future version.
