### ISSUE TITLE
compact function missing

### ISSUE THREAD

**Issue by Lusito** [scout-app/scout-app#336]
Related to #260 I guess:
Scout produces some wrong code where compass uses the function "compact".
I found this hotfix, but it would of course be nicer if it worked out of the box:
https://github.com/Igosuki/compass-mixins/issues/34#issuecomment-145603191

You can reproduce using this:
```scss
@import "compass/css3/transition";
#test {
    @include transition(width 0.5s);
}
```

that generates the following:
```css
#test {
  -webkit-transition: compact(compact(width 0.5s, false, false, false, false, false, false, false, false, false) false false...);
  -moz-transition: compact(compact(width 0.5s, false, false, false, false, false, false, false, false, false) false false false...);
  -o-transition: compact(compact(width 0.5s, false, false, false, false, false, false, false, false, false) false false false...);
  transition: compact(width 0.5s, false, false, false, false, false, false, false, false, false);
}
```

I'm using v2.12.12

**Comment by TheJaredWilcurt** [comment]
@Lusito 

This is not a Scout-App bug, it *was* a bug in the `compass-mixins` library though.

They resolved it in `0.12.8`. Scout-App ships with a copy of the latest version (`0.12.10`) for convenience. Their fix works if you import all of the `compass-mixins`, not just one specific file from it (`_transition.scss`).

If you change your code to this, it will work:

```sass
@import "compass";

#test {
    @include transition(width 0.5s);
}
```

It will then produce:

```css
#test {
  -webkit-transition: width 0.5s;
  -moz-transition: width 0.5s;
  -o-transition: width 0.5s;
  transition: width 0.5s;
}
```

Also, you probably don't need these vendor prefixes anyways:

* http://caniuse.com/#feat=css-transitions
