### ISSUE TITLE
Color definitions error with embedded variable definitions

### ISSUE THREAD

**Issue by rick9004** [scout-app/scout-app#360]
**OS:** Windows 10
**Scout-App Version:** 2.12.12
**Information from Dev Tools:**

Many errors when parsing Bootstrap 4 Beta A release due to this type of error

```
argument `$color` of `rgba($color, $alpha)` must be a color
```

From the Bootstrap file 

```scss
// custom file
  .custom-file-input {
    .was-validated &:#{$state},
    &.is-#{$state} {
      ~ .custom-file-control {
        border-color: $color;

        &::before { border-color: inherit; }
      }
      &:focus {
        box-shadow: 0 0 0 .2rem rgba($color,.25);
      }
```

Program seems not to be able to accept a previouly defined variable in the defniition of another variable.
