### ISSUE TITLE
Unicode Values Stored In Variables Are Not Processed Correctly

### ISSUE THREAD

**Issue by Willabee** [scout-app/scout-app#416]
I am using the latest Scout-App version on Windows 10 and all has been going well to help me learn SCSS.

Having just downloaded [Font-Awesome 4.7.0 SCSS files](https://fontawesome.com/v4.7.0/get-started/) and set up a project, I have noticed a problem with unicode output. As an example:

in the '_variables.scss' partial, we have:

    $fa-css-prefix: fa;
    $fa-var-music: "\f001";

and in '_icons.scss' partial, we have:

    .#{$fa-css-prefix}-music:before { content: $fa-var-music; }

with an expected result of:

    .fa-music:before { content: "\f001"; }

but the output is:

    .fa-music:before { content: ""; }

So all the unicode values stored in variables are processed to ``

Thus I am unable to correctly compile the correct CSS output with Scout-App.

I have tried placing UTF8 encoding at the top of each SCSS file:

    @charset "UTF-8";

but this proves not to be a solution.

**Comment by TheJaredWilcurt** [comment]
According to Stack Overflow, this is a known issue with Node-Sass (what Scout-App is using under the hood).

* https://stackoverflow.com/questions/25488037/sass-compile-fontawesome-preserve-notation
* https://stackoverflow.com/questions/30421570/sass-unicode-escape-is-not-preserved-in-css-file

Tested in all previous versions of Scout-App 2 and the issue occurred. Tested the code in [SassMeister](https://sassmeister.com), the issue still exists in the latest Dart-Sass release.

Changing your code from this:

```scss
@charset 'utf-8';

$fa-css-prefix: fa;
$fa-var-music: '\f001';

.#{$fa-css-prefix}-music:before {
    content: $fa-var-music;
}
```
to this
```scss
@charset 'utf-8';

@function unicode ($str) {
    @return unquote('"') + unquote(str-insert($str, '\\', 1)) + unquote('"');
}

$fa-css-prefix: fa;
$fa-var-music: f001;

.#{$fa-css-prefix}-music:before {
    content: unicode($fa-var-music);
}
```
Seems to make it work. This work around is the only solution I could find that works.

Closing as this issue is related to Sass, not Scout-App (which just uses Sass under the hood).
