### ISSUE TITLE
Can't use Line Breaks

### ISSUE THREAD

**Issue by lavathor** [scout-app/scout-app#453]
OS: 
Scout-App Version: 
Information from Dev Tools: 

![image](https://user-images.githubusercontent.com/22137684/155803026-274ee0cf-c006-4714-af16-751c699002a0.png)

**Comment by TheJaredWilcurt** [comment]
A `.sass` file does not use curly braces or semicolons.

`file.sass`
```sass
.example
    color: #F00
    border: 0px
```

`file.scss`
```scss
.example {
    color: #F00;
    boder: 0px;
}
```

I suspect that is the issue, but have not ran locally to verify.
